apiVersion: v1
kind: Pod
metadata:
  name: tshark-collector-pod
spec:
  containers:
  - image: quay.io/mwasher/tshark
    name: tshark-collection
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - mountPath: /host
      name: host
  hostNetwork: true
  hostPID: true
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /
      type: Directory
    name: host
