apiVersion: v1
kind: Pod
metadata:
  name: target-pod
spec:
  containers:
  - image: quay.io/libpod/alpine:latest
    name: target-pod
    command:
    - sh
    - -c
    - "while : ; do if [[ -f '/tmp/test-fail' ]] ; then  echo 'failed' ; else echo 'passed' ; touch /tmp/test-file; fi ; sleep 1; done"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
